spring.application.name=API-GATEWAY


spring.config.import=optional:configserver:http://localhost:8888

eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.reactive=TRACE

#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.access=unrestricted

logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=TRACE

# AUTH SERVICE

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=name=authCircuitBreaker,fallbackUri=forward:/fallback/auth
